name: ${project.name}
version: ${project.version}
description: ${project.description}
main: ${project.groupId}.${project.name}Plugin
author: PureGero
api-version: 1.20
folia-supported: true
multipaper-supported: true
commands:
  invisibleitemframes:
    description: "Make an item frame invisible"
    permission: "invisibleitemframes.toggle"
    aliases: ["itf"]
permissions:
  invisibleitemframes.toggle:
    default: op